spring:
  application:
    name: name
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: practica
    password: qwerty123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
